apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    name: test
  namespace: k8s-demo
spec:
  ports:
  - protocol: TCP
    port: 8079
    targetPort: 8079
  selector:
    name: test
  type: LoadBalancer
